<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Ifml" nsURI="ifmlUri" nsPrefix="ifmlPrefix">
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outInteractionFlows" lowerBound="1"
        upperBound="-1" eType="#//InteractionFlow" containment="true" eOpposite="#//InteractionFlow/sourceInteractionFlowElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inInteractionFlows" upperBound="-1"
        eType="#//InteractionFlow" eOpposite="#//InteractionFlow/targetInteractionflowelement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceInteractionFlowElement"
        lowerBound="1" eType="#//InteractionFlowElement" eOpposite="#//InteractionFlowElement/outInteractionFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetInteractionflowelement"
        lowerBound="1" eType="#//InteractionFlowElement" eOpposite="#//InteractionFlowElement/inInteractionFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlowExpression"
        eType="#//InteractionFlowExpression" eOpposite="#//InteractionFlowExpression/interactionFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationFlow" eSuperTypes="#//InteractionFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//InteractionFlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionflowExpression"
        eType="#//InteractionFlowExpression" containment="true" eOpposite="#//InteractionFlowExpression/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationExpression" eType="#//ActivationExpression"
        eOpposite="#//ActivationExpression/event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatchingEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionEvent" eSuperTypes="#//CatchingEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/actionEvents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElementEvent" eSuperTypes="#//CatchingEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewElement" lowerBound="1"
        eType="#//ViewElement" eOpposite="#//ViewElement/viewElementEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnSubmitEvent" eSuperTypes="#//ViewElementEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnSelectEvent" eSuperTypes="#//ViewElementEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//InteractionFlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewContainer" eType="#//ViewContainer"
        eOpposite="#//ViewContainer/inputPorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionEvents" upperBound="-1"
        eType="#//ActionEvent" containment="true" eOpposite="#//ActionEvent/action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewComponentPart" eSuperTypes="#//InteractionFlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewComponent" lowerBound="1"
        eType="#//ViewComponent" eOpposite="#//ViewComponent/viewComponentParts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationExpression" eType="#//ActivationExpression"
        eOpposite="#//ActivationExpression/viewComponentPart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElement" eSuperTypes="#//InteractionFlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewcontainer" eType="#//ViewContainer"
        eOpposite="#//ViewContainer/viewElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationExpression" eType="#//ActivationExpression"
        eOpposite="#//ActivationExpression/viewElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewElementEvent" upperBound="-1"
        eType="#//ViewElementEvent" containment="true" eOpposite="#//ViewElementEvent/viewElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewContainer" eSuperTypes="#//ViewElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//Action" containment="true" eOpposite="#//Action/viewContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewElements" upperBound="-1"
        eType="#//ViewElement" containment="true" eOpposite="#//ViewElement/viewcontainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewComponent" eSuperTypes="#//ViewElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewComponentParts" upperBound="-1"
        eType="#//ViewComponentPart" containment="true" eOpposite="#//ViewComponentPart/viewComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//ViewComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//ViewComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewComponentMenu" eSuperTypes="#//ViewComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivationExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"
        eOpposite="#//Event/activationExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewElement" eType="#//ViewElement"
        eOpposite="#//ViewElement/activationExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewComponentPart" eType="#//ViewComponentPart"
        eOpposite="#//ViewComponentPart/activationExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFlowExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionFlow" lowerBound="2"
        upperBound="-1" eType="#//InteractionFlow" eOpposite="#//InteractionFlow/interactionFlowExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//Event"
        eOpposite="#//Event/interactionflowExpression"/>
  </eClassifiers>
</ecore:EPackage>
